const data = [
  {
    id: 1,
    name: "Ice Queen",
    lat: 45.5084,
    long: -122.6544,
    type: "dessert",
    neighborhood: "SE",
    visited: false
  },
  {
    id: 2,
    name: "Concourse Coffee",
    lat: 45.5237,
    long: -122.6573,
    type: "coffee",
    neighborhood: "SE",
    visited: false
  },
  {
    id: 3,
    name: "Kachka",
    lat: 45.5157,
    long: -122.6571,
    type: "restaurant",
    neighborhood: "SE",
    visited: false,
  },
  {
    id: 4,
    name: "Eastside Coffee Bar & Workspace",
    lat: 45.5132,
    long: -122.6458,
    type: "coffee",
    neighborhood: "SE",
    visited: false,
  },
  {
    id: 5,
    name: "Honey Latte Cafe",
    lat: 45.5138,
    long: -122.655,
    type: "coffee",
    neighborhood: "SE",
    visited: false,
  },
  {
    id: 6,
    name: "Doe Donuts",
    lat: 45.5352,
    long: -122.6211,
    type: "dessert",
    neighborhood: "NE",
    visited: false,
  },
  {
    id: 7,
    name: "Miss Delta",
    lat: 45.5516,
    long: -122.6753,
    type: "restaurant",
    neighborhood: "N",
    visited: false,
  },
  {
    id: 8,
    name: "Screen Door",
    lat: 45.5238,
    long: -122.6827,
    type: "restaurant",
    neighborhood: "DT",
    visited: false,
  },
  {
    id: 9,
    name: "Grits N' Gravy",
    lat: 45.5221,
    long: -122.6771,
    type: "restaurant",
    neighborhood: "DT",
    visited: false,
  },
  {
    id: 10,
    name: "Less and more coffee",
    lat: 45.5165,
    long: -122.6788,
    type: "coffee",
    neighborhood: "DT",
    visited: false,
  },
  {
    id: 11,
    name: "Kalesa Coffee",
    lat: 45.5395,
    long: -122.6734,
    type: "coffee",
    neighborhood: "N",
    visited: false,
  },
  {
    id: 12,
    name: "Seven Virtues",
    lat: 45.5119,
    long: -122.6278,
    type: "coffee",
    neighborhood: "SE",
    visited: true,
  },
  {
    id: 13,
    name: "Dragonfly Coffee",
    lat: 45.5355,
    long: -122.7005,
    type: "coffee",
    neighborhood: "DT",
    visited: false,
  },
  {
    id: 14,
    name: "Black Water",
    lat: 45.5352,
    long: -122.6567,
    type: "restaurant",
    neighborhood: "SE",
    visited: false,
  },
  {
    id: 15,
    name: "Bao Bao",
    lat: 45.5237,
    long: -122.66,
    type: "restaurant",
    neighborhood: "SE",
    visited: false,
  },
  {
    id: 16,
    name: "Upper Left Roasters",
    lat: 45.5113,
    long: -122.6534,
    type: "coffee",
    neighborhood: "SE",
    visited: false,
  },
  {
    id: 17,
    name: "Symphony Coffee",
    lat: 45.5299,
    long: -122.8436,
    type: "coffee",
    neighborhood: "Other",
    visited: false,
  },
  {
    id: 18,
    name: "Brickhaus Coffee",
    lat: 45.4909,
    long: -122.8073,
    type: "coffee",
    neighborhood: "Other",
    visited: false,
  },
  {
    id: 19,
    name: "The Bulgogi + Dukuhbee Noodle",
    lat: 45.5362,
    long: -122.6192,
    type: "restaurant",
    neighborhood: "Other",
    visited: false,
  },
  {
    id: 20,
    name: "Mikiko Mochi Donuts",
    lat: 45.4915,
    long: -122.8279,
    type: "dessert",
    neighborhood: "Other",
    visited: false,
  },
  {
    id: 21,
    name: "Sinful Confections",
    lat: 45.4597,
    long: -122.7091,
    type: "dessert",
    neighborhood: "Other",
    visited: false,
  },
  {
    id: 22,
    name: "Kulfi",
    lat: 45.549,
    long: -122.6665,
    type: "dessert",
    neighborhood: "N",
    visited: false,
  },
  {
    id: 23,
    name: "Rukdiew",
    lat: 45.5162,
    long: -122.6393,
    type: "restaurant",
    neighborhood: "SE",
    visited: true,
  },
  {
    id: 24,
    name: "Dough Zone",
    lat: 45.5081,
    long: -122.6724,
    type: "restaurant",
    neighborhood: "DT",
    visited: true,
  },
  {
    id: 25,
    name: "Cubo",
    lat: 45.5118,
    long: -122.6336,
    type: "restaurant",
    neighborhood: "SE",
    visited: true,
  },
  {
    id: 26,
    name: "Koku Ramen & Bites",
    lat: 45.5152,
    long: -122.8874,
    type: "restaurant",
    neighborhood: "Other",
    visited: true,
  },
  {
    id: 27,
    name: "Tov Coffee & Tea",
    lat: 45.5121,
    long: -122.6325,
    type: "coffee",
    neighborhood: "SE",
    visited: true,
  },
  {
    id: 28,
    name: "Pip's Original Doughnuts & Chai",
    lat: 45.5484,
    long: -122.6138,
    type: "dessert",
    neighborhood: "NE",
    visited: true,
  },
  {
    id: 29,
    name: "Urban Creperie",
    lat: 45.5205,
    long: -122.6845,
    type: "restaurant",
    neighborhood: "DT",
    visited: false,
  },
  {
    id: 30,
    name: "Hunny Milk",
    lat: 45.5232,
    long: -122.6946,
    type: "restaurant",
    neighborhood: "DT",
    visited: false,
  },
  {
    id: 31,
    name: "AFURI ramen + dumpling Beaverton",
    lat: 45.4865,
    long: -122.8082,
    type: "restaurant",
    neighborhood: "Other",
    visited: true
  },
  {
    id: 32,
    name: "Palomar",
    lat: 45.5053,
    long: -122.6564,
    type: "restaurant",
    neighborhood: "SE",
    visited: true
  },
  {
    id: 33,
    name: "Jade Rabbit at the Emerald Room",
    lat: 45.5288,
    long: -122.6439,
    type: "restaurant",
    neighborhood: "SE",
    visited: false
  },
  {
    id: 34,
    name: "Roasted by Mom",
    lat: 45.5337,
    long: -122.8983,
    type: "coffee",
    neighborhood: "Other",
    visited: false
  },
  {
    id: 35,
    name: "Dos Hermanos",
    lat: 45.5194,
    long: -122.6554,
    type: "coffee",
    neighborhood: "Other",
    visited: false
  },
  {
    id: 36,
    name: "Wei Wei - A Taste of Taiwan",
    lat: 45.4681,
    long: -122.6533,
    type: "restaurant",
    neighborhood: "SE",
    visited: false
  },
  {
    id: 37,
    name: "Eem - Thai BBQ & Cocktails",
    lat: 45.5506,
    long: -122.6665,
    type: "restaurant",
    neighborhood: "SE",
    visited: false
  },
  {
    id: 38,
    name: "Double Dragon",
    lat: 45.5049,
    long: -122.6532,
    type: "restaurant",
    neighborhood: "SE",
    visited: true
  }
];


export default data;
