// template
// {
//     id: 1,
//         name: "",
//         lat: ,
//         long: ,
//         type: "", dessert, coffee, restaurant
//         neighborhood: "", SE, NE, NW, DT, other? or beav
//         visited: false, boolean
// }

const data = [
    {
        id: 1,
        name: "Ice Queen",
        lat: 45.508409,
        long: -122.6544966,
        type: "dessert",
        neighborhood: "SE",
        visited: false,
    },
    {
        id: 2,
        name: "Concourse Coffee",
        lat: 45.5237655,
        long: -122.6573791,
        type: "coffee",
        neighborhood: "SE",
        visited: false
    },
    {
        id: 3,
        name: "Kachka",
        lat: 45.5157393,
        long: -122.6571317,
        type: "restaurant",
        neighborhood: "SE",
        visited: false
    },
    {
        id: 4,
        name: "Eastside Coffee & Workspace",
        lat: "",
        long: "",
        type: "coffee", 
        neighborhood: "SE", 
        visited: false, 
    },
    {
        id: 5,
        name: "Honey Latte",
        lat: "",
        long: "",
        type: "coffee", 
        neighborhood: "SE", 
        visited: false, 
    },
    {
        id: 6,
        name: "Doe Donuts",
        lat: "",
        long: "",
        type: "dessert", 
        neighborhood: "NE", 
        visited: false, 
    },
    {
        id: 7,
        name: "Miss Delta",
        lat: "",
        long: "",
        type: "restaurant", 
        neighborhood: "NE", 
        visited: false, 
    },
    {
        id: 8,
        name: "Screen Door",
        lat: "",
        long: "",
        type: "restaurant", 
        neighborhood: "DT", 
        visited: false, 
    },
    {
        id: 9,
        name: "Grits and Gravy",
        lat: "",
        long: "",
        type: "restaurant", 
        neighborhood: "DT", 
        visited: false, 
    },
    {
        id: 10,
        name: "Less & More Coffee",
        lat: "",
        long: "",
        type: "coffee", 
        neighborhood: "DT", 
        visited: false, 
    },
    {
        id: 11,
        name: "Kalesa Coffee",
        lat: "",
        long: "",
        type: "coffee", 
        neighborhood: "DT", 
        visited: false, 
    },
    {
        id: 12,
        name: "Seven Virtues",
        lat: "",
        long: "",
        type: "coffee", 
        neighborhood: "SE", 
        visited: false, 
    },
    {
        id: 13,
        name: "Dragonfly Coffee",
        lat: "",
        long: "",
        type: "coffee", 
        neighborhood: "DT", 
        visited: false, 
    },
    {
        id: 14,
        name: "Black Water",
        lat: "",
        long: "",
        type: "restaurant", 
        neighborhood: "SE", 
        visited: false, 
    },
    {
        id: 15,
        name: "Bao Bao",
        lat: "",
        long: "",
        type: "restaurant", 
        neighborhood: "SE", 
        visited: false, 
    },
    {
        id: 16,
        name: "Upper Left Roasters",
        lat: "",
        long: "",
        type: "coffee", 
        neighborhood: "SE", 
        visited: false, 
    },
    {
        id: 17,
        name: "Symphony Coffee",
        lat: "",
        long: "",
        type: "coffee", 
        neighborhood: "SE", 
        visited: false, 
    },
    {
        id: 18,
        name: "Brickhaus Coffee",
        lat: "",
        long: "",
        type: "coffee", 
        neighborhood: "Other", 
        visited: false, 
    },
    {
        id: 19,
        name: "The Bulgogi and Dukuhbee Noodle",
        lat: "",
        long: "",
        type: "restaurant", 
        neighborhood: "Other", 
        visited: false, 
    },
    {
        id: 20,
        name: "Mikiko Mochi Donuts",
        lat: "",
        long: "",
        type: "dessert", 
        neighborhood: "Other", 
        visited: false, 
    },
    {
        id: 21,
        name: "Sinful Creations",
        lat: "",
        long: "",
        type: "dessert", 
        neighborhood: "Other", 
        visited: false, 
    },
    {
        id: 22,
        name: "Kulfi",
        lat: "",
        long: "",
        type: "dessert", 
        neighborhood: "SE", 
        visited: false, 
    },
    {
        id: 23,
        name: "Rukdiew",
        lat: "",
        long: "",
        type: "restaurant", 
        neighborhood: "SE", 
        visited: true, 
    },
    {
        id: 24,
        name: "Dough Zone",
        lat: "",
        long: "",
        type: "restaurant", 
        neighborhood: "DT", 
        visited: true, 
    },
    {
        id: 25,
        name: "Cubo",
        lat: "",
        long: "",
        type: "restuarant", 
        neighborhood: "SE", 
        visited: true, 
    },
    {
        id: 26,
        name: "Koku Ramen & Bites",
        lat: "",
        long: "",
        type: "restaurant", 
        neighborhood: "Other", 
        visited: true, 
    },
    {
        id: 27,
        name: "Tov Coffee",
        lat: "",
        long: "",
        type: "coffee", 
        neighborhood: "SE", 
        visited: true, 
    },
    {
        id: 28,
        name: "Pip's Doughnuts",
        lat: "",
        long: "",
        type: "dessert", 
        neighborhood: "NE", 
        visited: true, 
    }
]

export default data